log syslog all;

include "static.conf";
include "filter.conf";

router id OWNIP_S;

protocol kernel kernel {
    ipv6 {
        import none;
        export filter export_filter;
    };

    scan time 30;
    learn on;
    merge paths on;
    graceful restart on;
    metric 100;
}

protocol device {
    scan time 10;
}

protocol direct {
    ipv6;
}

include "transit/*.conf";
include "peers/*.conf";
include "ibgp/*.conf";
