log syslog all;

include "static.conf";
include "filter.conf";

router id OWNIP_S;

protocol kernel kernel_v4 {
    ipv4 {
        import none;
        export where export_filter(COMMUNITY_CUSTOMER, 0);
    };

    scan time 30;
    learn on;
    merge paths on;
    graceful restart on;
    metric 100;
}

protocol kernel kernel_v6 {
    ipv6 {
        import none;
        export where export_filter(COMMUNITY_CUSTOMER, 0);
    };

    scan time 30;
    learn on;
    merge paths on;
    graceful restart on;
    metric 100;
}

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    ipv6 {
        import where net !~ OWNNETv6;
        export none;
    };
}

include "peers/*.conf";
#include "ibgp/*.conf";