define LOCAL_NETS_V4 = [
    # RFC 1918
    10.0.0.0/8+,         # 10.0.0.0 - 10.255.255.255
    172.16.0.0/12+,      # 172.16.0.0 - 172.31.255.255
    192.168.0.0/16+,     # 192.168.0.0 - 192.168.255.255
    
    # RFC 6598 Carrier-grade NAT
    100.64.0.0/10+,      # 100.64.0.0 - 100.127.255.255
    
    # RFC 3927
    169.254.0.0/16+,     # 169.254.0.0 - 169.254.255.255
    
    # Loopback
    127.0.0.0/8+,        # 127.0.0.0 - 127.255.255.255
    
    # RFC 6890
    0.0.0.0/8+,          # "this" network
    192.0.0.0/24+,       # IETF
    192.0.2.0/24+,       # TEST-NET-1
    198.18.0.0/15+,
    198.51.100.0/24+,    # TEST-NET-2
    203.0.113.0/24+,
    224.0.0.0/4+,
    240.0.0.0/4+
];


define LOCAL_NETS_V6 = [
    # RFC 4193
    fd00::/8+,           # fd00::/8 - fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    
    # RFC 4291
    ::1/128+,            # Loopback
    
    # RFC 4291
    ::/128+,
    
    # RFC 4291
    fe80::/10+,          # fe80:: - febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    
    # RFC 4193
    fec0::/10+,          # fec0:: - feff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    
    # RFC 4291
    ff00::/8+,           # ff00:: - ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    
    # RFC 4843
    2001:db8::/32+,      # 2001:db8:: - 2001:db8:ffff:ffff:ffff:ffff:ffff:ffff
    
    # 6to4
    2002::/16+,          # 2002:: - 2002:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    
    # Teredo
    2001::/32+,          # 2001:: - 2001:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    
    # ORCHID
    2001:10::/28+,       # 2001:10:: - 2001:1f:ffff:ffff:ffff:ffff:ffff:ffff
    
    # ORCHIDv2
    2001:20::/28+,       # 2001:20:: - 2001:2f:ffff:ffff:ffff:ffff:ffff:ffff

    fc00::/7+,
];

function is_local_net_v4()
{
    return net ~ LOCAL_NETS_V4;
}

function is_local_net_v6()
{
    return net ~ LOCAL_NETS_V6;
}

function is_valid_prefix_v4() {
    if net.len < 8 || net.len > 24 then return false;
    if net = 0.0.0.0/0 then return false;
    return true;
}

function is_valid_prefix_v6() {
    if net.len < 8 || net.len > 48 then return false;
    if net = ::/0 then return false;
    return true;
}

function is_valid_prefix() {
    case net.type { 
        NET_IP4: return is_valid_prefix_v4();
        NET_IP6: return is_valid_prefix_v6();
    }
}

function local_and_bogon() {
    if is_local_net_v4() then {
        print "Rejecting IPv4 local network: ", net;
        return true;
    }
    
    if is_local_net_v6() then {
        print "Rejecting IPv6 local network: ", net;
        return true;
    }

    if !is_valid_prefix() then {
        return true;
    }
    
    return false;
}

filter import_filter {
    if local_and_bogon() then reject;
    
    accept;
}

filter export_filter {
    # reject local
    if local_and_bogon() then reject;
    # export static and bgp
    if source !~ [RTS_STATIC, RTS_BGP] then reject;
    # Set SRC
    krt_prefsrc = OWNIPv6;
    accept;
}
