define OWNAS = 204211;

# MyNet Address
define OWNIPv4 = 1.1.1.1;
define OWNIPv6 = ::0;
define OWNNETv6 = ::0/0;
define OWNNETSETv6 = [ ::0/0+ ];

protocol static static {
    ipv6;
    route OWNNETv6 via "eth0";
}
