# iBGP Route Reflector
protocol bgp rr1 {
    description "Connection to Route Reflector 1";
    local as OWNAS;
    neighbor 100.114.51.4 as OWNAS;
    
    connect delay time 2;
    connect retry time 5;
    hold time 90;
    keepalive time 15;
    
    ipv6 {
        import where import_filter(0);
        export where export_filter(209);
        next hop self;
    };
}
