protocol bgp ibgp_fra {
    local as OWNAS;
    direct;
    neighbor as OWNAS;

    hold time 90;
    keepalive time 15;

    ipv6 {
        import where import_filter(COMMUNITY_IBGP, 249);
        export where export_filter(COMMUNITY_IBGP, 204211);
        next hop self;
    };
}