protocol bgp rr1 {
    description "Connection to Route Reflector 1";
    local as OWNAS;
    neighbor 100.114.51.4 as OWNAS;
    
    connect delay time 2;
    connect retry time 5;
    hold time 90;
    keepalive time 15;
    
    ipv6 {
        import filter import_filter;
        export filter export_filter;
        next hop self;
    };
}
